# Generated by Django 6.0.7 on 2026-09-21 19:08

import django.db.models.deletion
import modelcluster.fields
import modelsearch.index
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_conformes_blog', '0061_alter_blogentrypage_body_alter_blogindexpage_body_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Thème',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', wagtail.fields.RichTextField(verbose_name='Réponse')),
                ('date', models.DateField(blank=True, help_text='Date de la réponse ou de sa dernière mise à jour (non affichée).', null=True, verbose_name='Date')),
                ('link_url', models.URLField(blank=True, default='', help_text='Ignoré si un lien interne est renseigné.', max_length=2000, verbose_name='Lien externe')),
                ('authors', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Les auteurs se créent dans Fragments > Personnes. Affichés en italique au-dessus de la réponse (rôle - nom - organisation).', to='sites_conformes_blog.person', verbose_name='Auteurs')),
                ('link_page', models.ForeignKey(blank=True, help_text='Affiché en bouton « En savoir plus » sous la réponse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Lien interne')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='sites_conformes_faq.theme', verbose_name='Thème')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['question'],
            },
            bases=(wagtail.models.preview.PreviewableMixin, modelsearch.index.Indexed, models.Model),
        ),
    ]
