# Generated by Django 6.0.7 on 2026-09-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='link_text',
            field=models.CharField(blank=True, default='', help_text='« En savoir plus » si vide.', max_length=255, verbose_name='Texte du lien'),
        ),
    ]
