# Generated by Django 6.0.7 on 2026-09-25 13:00

import datetime
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_blog', '0064_recent_events_block__see_all_events_link'),
        ('sites_conformes_faq', '0002_question_link_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_authors',
            field=models.BooleanField(default=False, help_text='En italique au-dessus de la réponse (rôle - nom - organisation). Sinon les auteurs restent une information interne.', verbose_name='Afficher les auteurs'),
        ),
        migrations.AlterField(
            model_name='question',
            name='authors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Les auteurs se créent dans Fragments > Personnes.', to='sites_conformes_blog.person', verbose_name='Auteurs'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Date de la réponse ou de sa dernière mise à jour (non affichée).', null=True, verbose_name='Date'),
        ),
    ]
