# Generated by Django 6.0.7 on 2026-07-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerpartnerssettings',
            name='logo_height',
            field=models.DecimalField(decimal_places=3, default='5.625', help_text='Applied to every partner logo so they share a uniform height, as recommended by the DSFR.', max_digits=4, verbose_name='Logo height (rem)'),
        ),
        migrations.AlterField(
            model_name='footerpartnerssettings',
            name='main_partner_alt',
            field=models.CharField(blank=True, default='', help_text="Required if a main partner logo is set. Must be the partner's name.", max_length=200, verbose_name='Main partner logo alt text'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='alt',
            field=models.CharField(help_text="Must be the partner's name.", max_length=200, verbose_name='Alt text'),
        ),
    ]
