# Generated by Django 6.0.7 on 2026-07-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_footerpartnerssettings_logo_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerpartnerssettings',
            name='logo_height',
            field=models.DecimalField(decimal_places=3, default='5.625', help_text='Applied to every logo for a uniform height, as recommended by the DSFR.', max_digits=4, verbose_name='Logo height (rem)'),
        ),
    ]
