# Generated by Django 6.0.7 on 2026-07-29 12:07

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterPartnersSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Example: "Ce site est développé et financé par" or "Ils nous soutiennent".',
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "main_partner_alt",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Must contain the text present in the image.",
                        max_length=200,
                        verbose_name="Main partner logo alt text",
                    ),
                ),
                (
                    "main_partner_url",
                    models.URLField(
                        blank=True, default="", max_length=2000, verbose_name="Main partner link"
                    ),
                ),
                (
                    "main_partner_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Main partner logo",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer partners",
            },
        ),
        migrations.CreateModel(
            name="PartnerLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "alt",
                    models.CharField(
                        help_text="Must contain the text present in the image.",
                        max_length=200,
                        verbose_name="Alt text",
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, default="", max_length=2000, verbose_name="Link"),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "settings",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_partners",
                        to="sites_conformes_footer_partners.footerpartnerssettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner logo",
                "verbose_name_plural": "Partner logos",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
