# Generated by Django 6.0.7 on 2026-07-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_database_id', models.CharField(blank=True, default='', help_text="The UUID found in the Notion database's URL. Share it with your integration.", max_length=100, verbose_name='Notion database ID')),
                ('form_page', models.ForeignKey(blank=True, help_text='The form page to sync. Must have exactly 4 fields, in this order: name, email, subject, message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Contact form page')),
            ],
            options={
                'verbose_name': 'Notion contact sync',
            },
        ),
    ]
