terraform {
  required_providers {
    scaleway = {
      source  = "scaleway/scaleway"
      version = "~> 2.50"
    }
  }
}

resource "scaleway_object_bucket" "this" {
  name   = var.bucket_name
  region = var.region
  tags = merge(
    {
      app         = var.app_name
      environment = var.environment
      managed_by  = "opentofu"
    },
    var.tags,
  )
}

resource "scaleway_object_bucket_acl" "this" {
  bucket = scaleway_object_bucket.this.id
  acl    = "private"
}

# ponytail: no app-scoped IAM application/policy/key here - the deploying
# Scaleway API key doesn't have IAM write permission yet, so cms reuses the
# same SCW_ACCESS_KEY/SCW_SECRET_KEY as everything else (passed in from
# envs/prod, not generated by this module). Revisit with a scoped
# application + bucket policy once that key's IAM rights are widened.
