name: OpenTofu plan

on:
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform-plan.yml"

env:
  TOFU_VERSION: "1.8.5"

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/envs/prod
    env:
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
      SCW_DEFAULT_ORGANIZATION_ID: ${{ secrets.SCW_DEFAULT_ORGANIZATION_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
      TF_VAR_vigilance_app_id: ${{ secrets.VIGILANCE_APP_ID }}
      TF_VAR_rte_client_id: ${{ secrets.RTE_CLIENT_ID }}
      TF_VAR_rte_client_secret: ${{ secrets.RTE_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}
          tofu_wrapper: false

      - run: tofu fmt -check -recursive
        working-directory: infra

      - run: tofu init -input=false

      - run: tofu validate

      - run: tofu plan -no-color -input=false
